### ISSUE TITLE
How i do whem i dont have the UUID?

### ISSUE THREAD

**Issue by alechristian** [matfire/bluetooth_classic#4]
Hello, There!

First, thanks for the library!

So, what do I do if I don't have the device's UUID? I'm now starting to study Bluetooth and from what I've seen, not all classic devices have UUID, I could be mistaken.

Thanks!

**Comment by matfire** [comment]
Hey,
Unfortunately you need a UUID in order to establish the connection. Each device can expose multiple UUIDs depending on the services they support (serial, audio). These UUiDs can either be customized (created by you for the specific use case), or you can also use the ones that are part of the spec. Usually a device should at least support the serial profile UUID (00001101-0000-1000-8000-00805F9B34FB), but I could be wrong.

If the device doesn't support any UUIDs, then you would not be able to connect to it using this library (or any implementing the Bluetooth standard)

**Comment by alechristian** [comment]
Oh no problem then, I'm trying to connect a weight scale and I don't have the manufacturer's documentation for it.

Thank you for your help!
